---
- name: Add grub customizer
  ansible.builtin.apt_repository:
    repo: ppa:danielrichter2007/grub-customizer
    state: present
  become: true

- name: Update grub
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install grub-customizer
  ansible.builtin.apt:
    name: grub-customizer
    state: present
  when: install_grub_customizer | default(false)
  become: true