---
# defaults file for samba

samba_workgroup: "WORKGROUP_CCEPL_DATASHARE"
samba_log_size: 5000

# samba_shares: []
samba_shares_root: "/opt/ccpldata/ccplnewdata"
first_samba_shares:
  - comment: "CCEPL data share"
    shardirname: CCEPL_SERVER
    browseable: "yes"
    read_only: "no"
    writable: "yes"
    guest_ok: "no"
    valid_users: cce
    group: cce
    vfs_audit: true

second_samba_shares:
  - sharename: second_cce_share_name
    shardirname: CCEPL_SERVER_SECOND
    comment: "cce second data share"
    browseable: "yes"
    read_only: "no"
    writable: "yes"
    guest_ok: "no"
    valid_users: cce
    group: cce

samba_users:
  - name: cce
    password: cce