---
# tasks file for onedrive_install

# - name: Add Release Key
#   shell: wget -qO - https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /usr/share/keyrings/obs-onedrive.gpg > /dev/null
# - name: Add OpenSuSE Repository
#   shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/obs-onedrive.gpg] https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/ ./" | sudo tee /etc/apt/sources.list.d/onedrive.list

- name: Update Repository
  shell: apt update

# - name: Inst - Onedrive Packages
#   ansible.builtin.package:
#     name: "{{ onedrive_packages }}"
#     state: "present"
#   tags: onedrive-inst-package
#   register: inst_onedrive

- name: Force purge the old broken OneDrive repository list file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/home:npreining:debian-ubuntu-onedrive.list
    state: absent
  become: true

- name: Clear apt cache to drop the bad package reference
  ansible.builtin.ansible.builtin.command: apt-get clean
  become: true

- name: Install OneDrive Package from official Ubuntu repositories
  ansible.builtin.apt:
    name: onedrive
    state: present
    update_cache: yes
  register: inst_onedrive
  tags: onedrive-inst-package
  become: true

- debug:
    var: inst_onedrive
  
- name: Onedrive Version
  shell: onedrive --version
  register: ver_onedrive

- debug:
    var: ver_onedrive.stdout_lines
